title: Environment
type: object
additionalProperties: false
required:
  - kind
  - name
  - deployServices
  - variables
properties:
  kind:
    const: "Environment"
  name:
    $ref: "./partials/name.yaml"
  deployServices:
    type: array
    items:
      $ref: "./partials/name.yaml"
  variables:
    type: object
    patternProperties:
      "^[a-zA-Z][a-zA-Z0-9]*$":
        type: string
