---
apiVersion: g2a-cli/v2.0
kind: service
name: generic-api
tags:
  # Usually it's better to use tag policies like "gitSha" or "gitTag", but we
  # need to test these examples, so tags should not change.
  - custom: "latest"
artifacts:
  - custom-docker:
      image: "example.com/test/image"
releases:
  - custom-helm:
      name: "generic-api-{{ .Environment.Name }}"
      chartPath: "example/chart"
      chartVersion: "v1.2.3"
      values:
        image: "example.com/test/image:{{ .Tag }}"
      chartRepository:
        name: example
        url: "https://example.com"
