title: Environment
type: object
required:
  - apiVersion
  - kind
  - name
properties:
  apiVersion:
    $ref: './partials/api-version.yaml'
  kind:
    description: Determines type of the document.
    const: 'Environment'
  name:
    description: Unique name used to identify environment.
    $ref: './partials/name.yaml'
  deployServices:
    description: >
      Default list of the services to deploy to this environment. It may be modified by using
      "--services" option.
    type: array
    items:
      $ref: './partials/name.yaml'
  variables:
    description: >
      Definitions of the variables to use in the configuration files. Names are case-insensitive.
    examples:
      - name: value
    type: object
    patternProperties:
      '^[a-zA-Z][a-zA-Z0-9]*$':
        type: string
